<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.crud</groupId>
	<artifactId>crud-empresa</artifactId>
	<version>0.0.1-SNAPSHOT</version>


	<packaging>war</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency> <!--CDI -->
			<groupId>org.jboss.weld.servlet</groupId> <!-- da mesma forma que o JPA é uma especificacao e o Hibernate é um implementacao, o CDI tambem é uma especificacao, o weld tambem é uma implementacao dela-->
			<artifactId>weld-servlet</artifactId>
			<version>2.4.0.Final</version>
			<scope>compile</scope>
		</dependency>
		
		<dependency>
			<groupId>org.glassfish</groupId> <!-- possui implementacao e especificacao que é o Mojarra -->
			<artifactId>javax.faces</artifactId>
			<version>2.3.9</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>14.0.0</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>javax.servlet</groupId> <!-- JPA -->
			<artifactId>javax.servlet-api</artifactId>
			<version>4.0.1</version>
			<scope>provided</scope> <!--não precisa empacotar dentro do pacote final, somente compile-->
		</dependency>

		<dependency> <!--dependencia de API de validacao-->
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>5.3.2.Final</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>5.2.4.Final</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.jboss.logging</groupId>
			<artifactId>jboss-logging</artifactId>
			<version>3.3.0.Final</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>6.0.5</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<name>crud-empresa</name>
	<description>JSF e primefaces</description>
</project>